import { Email } from '@/types/mail';

export const MOCK_EMAILS: Email[] = [
  {
    id: crypto.randomUUID(),
    from: 'John Doe <john@example.com>',
    fromName: 'John Doe',
    fromEmail: 'john@example.com',
    initials: 'JD',
    subject: 'Meeting Tomorrow',
    preview: 'Hey, just checking about tomorrow...',
    body: 'Full email body goes here...',
    date: new Date(Date.now() - 2 * 3600_000).toISOString(),
    unread: true,
    starred: false,
    category: 'primary',
  },
  {
    id: crypto.randomUUID(),
    from: 'Stripe <receipts@stripe.com>',
    fromName: 'Stripe',
    fromEmail: 'receipts@stripe.com',
    initials: 'ST',
    subject: 'Payment Processed',
    preview: 'Your recent transaction was successful',
    body: 'Receipt details...',
    date: new Date(Date.now() - 5 * 3600_000).toISOString(),
    unread: false,
    starred: false,
    category: 'updates',
  },
  {
    id: crypto.randomUUID(),
    from: 'GitHub <notifications@github.com>',
    fromName: 'GitHub',
    fromEmail: 'notifications@github.com',
    initials: 'GH',
    subject: 'New Pull Request',
    preview: 'A new PR has been opened',
    body: 'PR details...',
    date: new Date(Date.now() - 24 * 3600_000).toISOString(),
    unread: true,
    starred: false,
    category: 'updates',
  },
];
